### ISSUE TITLE
AttributeValue encode/decode like encoding/json

### ISSUE THREAD

**Issue by justonia** [smugmug/godynamo#14]
Thought you might be interested in this:

https://github.com/justonia/dynamodb-helpers

It's a high level interface to encode/decode objects to/from an AttributeValue into real types. I use it in an internal library and it's been pretty solid thus far.

**Comment by bradclawsie** [comment]
Nice! I'll take a look.

**Comment by bradclawsie** [comment]
Going to close this as it isn't really appropriate for a bug report, but still looks like an awesome library!
