### ISSUE TITLE
Can't install the lib anymore: goawsroles/roles/roles.go:71: undefined: aws.Credentials

### ISSUE THREAD

**Issue by cirpo** [smugmug/godynamo#16]
I can't use the library anymore because with the latest changes on goawroles lib the godynamo lib is broken:

running `go get github.com/smugmug/godynamo` I get:

`github.com/smugmug/goawsroles/roles/src/github.com/smugmug/goawsroles/roles/roles.go:71: undefined: aws.Credentials`

**Comment by doublefree** [comment]
go get github.com/smugmug/godynamo
# github.com/smugmug/goawsroles/roles
../../go/src/github.com/smugmug/goawsroles/roles/roles.go:71: undefined: aws.Credentials

same issue happens also for me

**Comment by cirpo** [comment]
godeps save my life last night :D

**Comment by bradclawsie** [comment]
I ran into this also and had to run

go get github.com/awslabs/aws-sdk-go/aws

I'm not sure why it didn't install automatically when this package is installed...any ideas?

**Comment by bradclawsie** [comment]
Hmmm, the aws-sdk package is moving too fast, the bindings I made are already obsoleted by changes they have made...I think for now I just need to remove this dependency

**Comment by bradclawsie** [comment]
I was wrong to try to bind to the aws-sdk-go, it is changing too quickly. I have removed references to it for   now and will add them back in at a later date when they have committed to a stable interface.
